// Auto-generated types from Sanity schema
// Do not edit this file manually

export interface Post {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: {
    _type: "slug";
    current: string;
  };
  publishedAt: string;
  image?: {
    _type: "image";
    asset: {
      _type: "reference";
      _ref: string;
    };
    alt?: string;
  };
  body: Array<{
    _type: "block";
    _key: string;
    style?: string;
    children: Array<{
      _type: "span";
      _key: string;
      text: string;
      marks?: string[];
    }>;
  }>;
}

export type SanityDocument = Post;
