// Auto-generated types from Sanity schema
// Do not edit this file manually

export interface Post {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: {
    _type: "slug";
    current: string;
  };
  publishedAt: string;
  category: "news" | "features" | "security" | "updates" | "tips" | "industry";
  tags?: string[];
  isFeatured?: boolean;
  image?: {
    _type: "image";
    asset: {
      _type: "reference";
      _ref: string;
    };
    alt?: string;
  };
  body: Array<{
    _type: "block" | "figure";
    _key: string;
    style?: string;
    children?: Array<{
      _type: "span";
      _key: string;
      text: string;
      marks?: string[];
    }>;
    // Figure type fields
    asset?: {
      _type: "reference";
      _ref: string;
    };
    alt?: string;
    caption?: string;
  }>;
}

export type SanityDocument = Post;
